### PR TITLE
Issue 48 plus commented dead code removed

### PR DESCRIPTION
**Pull request by martinberoiz**

### CODE REVIEW

**Comment by leliel12** [comment]
Maybe move logger as top-level variable is a god idea

**Comment by martinberoiz** [comment]
Sure. Top level in `__init__`?

**Comment by BrunoSanchez** [comment]
Check style, it fails in cov also, but not that relevant yet.

**Review by BrunoSanchez — APPROVED** [review]
This is great. Thanks for the logger implementation.

**Pull request merged**
